sonar.organization=ioanabianca
sonar.projectKey=tfm-juice-shop
sonar.projectName=TFM-JuiceShop-DevSecOps

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/test/**,**/k8s/**

sonar.sourceEncoding=UTF-8
sonar.language=js