apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-deployer
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-minimal-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"] # No permite borrar, crear o editar recursos

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-minimal-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pipeline-deployer
  namespace: default
roleRef:
  kind: Role
  name: app-minimal-role
  apiGroup: rbac.authorization.k8s.io